# Generated by Django 4.0.4 on 2022-04-21 15:57

import datetime
from django.db import migrations, models
import urlshortener.short_url


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(default=urlshortener.short_url.get_short_url, help_text='Short url', max_length=255, unique=True)),
                ('full_url', models.URLField(help_text='Source url', max_length=2000)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('creation_date', models.DateField(default=datetime.datetime.now)),
                ('count_clicked', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
