# Generated by Django 4.0.4 on 2022-05-01 21:19

from django.db import migrations, models
import urlshortener.short_url


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_alter_link_options_alter_link_count_clicked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='id',
        ),
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.CharField(default=urlshortener.short_url.get_short_url, help_text='Short url', max_length=255, primary_key=True, serialize=False, verbose_name='Короткая ссылка'),
        ),
    ]
