# Generated by Django 4.0.4 on 2022-05-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0003_remove_link_id_alter_link_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='count_clicked',
            field=models.IntegerField(default=0, verbose_name='Кол-во переходов'),
        ),
    ]
